name: build-release-stable
on:
  push:
    tags: 
      - 'v*'
    branches:
      - stellar

env:
  python_win_version: 3.11.8
  # release type this file is used for
  release: stable

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.9, 3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r build/requirements/linux.txt
    - name: Test with unittest
      run: python -m unittest tests/test_*.py

  windows-32:
    runs-on: windows-2022
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python_win_version }}
          architecture: x86
      #  no PyQt6 for win32 available on pypi.org
      - run: ((Get-Content -path build/requirements/windows.txt -Raw) -replace 'pyqt6.*','pyqt5') | Set-Content -Path build/requirements/windows.txt
      - run: python -m pip install --no-warn-script-location -r build/requirements/windows.txt
      # pretty hacky but no other idea to avoid gssapi being installed which breaks requests-kerberos
      - run: python -m pip uninstall -y gssapi requests-gssapi
      - run: cd ${{ github.workspace }}/build; python build.py
        env:
          PYTHONPATH: ${{ github.workspace }}
          WIN_SIGNING_CERT_BASE64: ${{ secrets.SIGNING_CERT_BASE64 }}
          WIN_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      - uses: actions/upload-artifact@v3
        with:
          path: |
            build/dist/*.zip
            build/dist/*.exe
          retention-days: 1
          if-no-files-found: error

  windows-64:
    runs-on: windows-2022
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python_win_version }}
          architecture: x64
      - run: python -m pip install --no-warn-script-location -r build/requirements/windows.txt
      # pretty hacky but no other idea to avoid gssapi being installed which breaks requests-kerberos
      - run: python -m pip uninstall -y gssapi requests-gssapi
      - run: cd ${{ github.workspace }}/build; python build.py
        env:
          PYTHONPATH: ${{ github.workspace }}
          WIN_SIGNING_CERT_BASE64: ${{ secrets.SIGNING_CERT_BASE64 }}
          WIN_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      - uses: actions/upload-artifact@v3
        with:
          path: |
            build/dist/*.zip
            build/dist/*.exe
          retention-days: 1
          if-no-files-found: error

  windows-64-debug:
    runs-on: windows-2022
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.python_win_version }}
          architecture: x64
      - run: python -m pip install --no-warn-script-location -r build/requirements/windows.txt
      # pretty hacky but no other idea to avoid gssapi being installed which breaks requests-kerberos
      - run: python -m pip uninstall -y gssapi requests-gssapi
      - run: cd ${{ github.workspace }}/build; python build.py debug
        env:
          PYTHONPATH: ${{ github.workspace }}
          WIN_SIGNING_CERT_BASE64: ${{ secrets.SIGNING_CERT_BASE64 }}
          WIN_SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
      - uses: actions/upload-artifact@v3
        with:
          path: |
            build/dist/*.zip
          retention-days: 1
          if-no-files-found: error

  github-release:
    runs-on: ubuntu-latest
    needs: [windows-32, windows-64, windows-64-debug]
    steps:
      - uses: actions/download-artifact@v3
      - run: cd artifact && md5sum *agstamon* > md5sums.txt
      - run: cd artifact && sha256sum *agstamon* > sha256sums.txt
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: true
          files: |
            artifact/*
